// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBz125Y3cTy2lq5waI7q4k17WIXBDPf0ek',
    appId: '1:984403060226:web:f7aee9333a5481dc02291b',
    messagingSenderId: '984403060226',
    projectId: 'ravestreammobileapp',
    authDomain: 'ravestreammobileapp.firebaseapp.com',
    storageBucket: 'ravestreammobileapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDy4Dw4xTKPNz2XqxKYNn_YnaBVYQmKG4c',
    appId: '1:984403060226:android:dad7709dd75477ed02291b',
    messagingSenderId: '984403060226',
    projectId: 'ravestreammobileapp',
    storageBucket: 'ravestreammobileapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6QnR-Olp8siLzqpX2i86cXGgq32ju7t4',
    appId: '1:984403060226:ios:e805b1edb2324f5f02291b',
    messagingSenderId: '984403060226',
    projectId: 'ravestreammobileapp',
    storageBucket: 'ravestreammobileapp.appspot.com',
    iosClientId: '984403060226-2mic36kktqh28ellrv55g5pd9u8k1r2e.apps.googleusercontent.com',
    iosBundleId: 'com.example.ravestreamradioapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6QnR-Olp8siLzqpX2i86cXGgq32ju7t4',
    appId: '1:984403060226:ios:e805b1edb2324f5f02291b',
    messagingSenderId: '984403060226',
    projectId: 'ravestreammobileapp',
    storageBucket: 'ravestreammobileapp.appspot.com',
    iosClientId: '984403060226-2mic36kktqh28ellrv55g5pd9u8k1r2e.apps.googleusercontent.com',
    iosBundleId: 'com.example.ravestreamradioapp',
  );
}
